export class CHARS {
  static SPACE = ' '
  static NEWLINE = '\n'
  static RETURN = '\r'
  static DOT = '.'
  static COMMA = ','
  static OPEN_BRACE = '{'
  static CLOSE_BRACE = '}'
  static OPEN_PAREN = '('
  static COLON = ':'
  static SEMICOLON = ';'
  static DOLLAR = '$'
  static LESS_THAN = '<'
  static GREATER_THAN = '>'
  static ASTERISK = '*'
  static SLASH = '/'
  static DOUBLE_SLASH = '//'
  static DOUBLE_HYPHEN = '--'
  static DOUBLE_QUOTE = '"'
}